### ISSUE TITLE
Is Firestore mock delete() not yet implemented?

### ISSUE THREAD

**Issue by jeunessacheng** [Upstatement/firestore-jest-mock#131]
# Summary
Making calls to `delete()` a document in a collection does not remove the document.

## Relevant information
Looking at `/node_modules/firestore-jest-mock/mocks/firestore.js`, the implementation for document deletion seems to be missing:
```
  delete() {
    mockDelete(...arguments);
    return Promise.resolve();
  }
```

**Comment by sbatson5** [comment]
It should exist on an instance of a document reference:
https://github.com/Upstatement/firestore-jest-mock/blob/80d43fb58a5fd38646fb71ed67362146687fc19b/mocks/firestore.js#L272-L275

Do you have an example of it not working?

**Comment by jeunessacheng** [comment]
I'm writing some unit tests with a mocked Firestore collection, and testing reading from the collection after the deletion to see if the document was removed.

```
await this.firestore.collection(COLLECTION_NAME).doc(docName).delete();
const items = await this.firestore.collection(COLLECTION_NAME).get();
items = items.docs.map(doc => doc.data());

// Check if item was removed from the collection
const removedItem = item.find( i => i.name === docName ); // Note that i.name is the same as document id
expect ( removedItem ).not.toBeDefined(); // This line fails, removedItem is still in the collection
```

**Comment by sbatson5** [comment]
Ah. Our `delete` does not actually mutate the mocked collection. Instead, you can check that `mockDelete` (the function that overrides our `delete` function) is called correctly, with the right params.

If our `delete` on the document reference actually removed the associated document from the fake collection and you asserted that it was removed, then all you would have done is tested that `firestore-jest-mock` has a function that remoes one item from an array. You wouldn't have actually tested _your_ code, which is what I would argue you would want in this case.

i.e. the way you want to use this library is:
`expect(mockDelete).toHaveBeenCalledWith(docName)`
you want to assert that you properly called the `delete` function -- not that the `delete` function actually did anything. That's firestore's concern, and since we completely overwrite firestore with this testing library, you would really be testing that the authors of this library wrote a function that deleted an item from a collection.

😅 I admit that it seems counter intuitive, but the point of this library is to enable you to test your code and how it interfaces with firestore -- not that firestore performs the actions appropriately.

Hope this helps! Happy to dive in further

**Comment by jeunessacheng** [comment]
Cool, thanks, I get it now.  I guess since I was able to test with `add` and `update`, I got high hopes for `delete` as well.  Thanks for answering so promptly!

**Comment by hffmnn** [comment]
> If our delete on the document reference actually removed the associated document from the fake collection and you asserted that it was removed, then all you would have done is tested that firestore-jest-mock has a function that remoes one item from an array. You wouldn't have actually tested your code, which is what I would argue you would want in this case.

I don't think this is the only use case for a working delete. Code under test could for example delete a document and based on a collection query return the remaining documents (or something like this... more general: the tested code relies on working mutations). If the delete does not mutate the collection, then the system under test behaves differently in tests.

Because this library supports mutability: Is there documentation about calls that mutate vs. calls that don't?

**Comment by AlmogCC** [comment]
I tend to agree with @hffmnn. If mutability wasn't supported the point made by @sbatson5 would be valid. Once mutation is supported, why would `delete` be the only method excluded from it?
