### ISSUE TITLE
Where query on nested fields

### ISSUE THREAD

**Issue by MorenoMdz** [Upstatement/firestore-jest-mock#134]
# Summary
Please correct me if I am wrong, but right now there is no support for querying on nested fields? For example, the code `.where("info.startTime", ">=", serverTime)` does not work and will not match any documents. Doing the same check on a field that is in the root of the document works fine with `simulateQueryFilters` set to true.

Is there a way to enable this, or perhaps have this a future feature?

Once again, thank you very much for all the hard work done here.

**Comment by sbatson5** [comment]
You're right, there isn't currently support for that. I feel like this starts to get into the area of "how much behavior do we reproduce?" If we write a code in this repo to allow for querying nested keys, then the tests we write against this mock are really only testing _this_ repo and not necessarily firestore or your code.

I just worry we'll spend a lot of time writing a ton of complicated code and users won't actually be testing anything useful

**Comment by sbatson5** [comment]
I can certainly be convinced (have been in the past with other functions here). I guess my question is, what would your test look like. Is it something like:

```
db.collection('animals').where('species.type', '==', 'mammal').then((snapshot => {
  snapshot.forEach(doc => expect(doc.data().type).toEqual('mammal'));
});
```

We query for mammals in our nested field and we assert that all the ones returned are of the type: mammal. In my opinion, what is written above isn't a useful test, since it really only tests that `firestore-jest-mock` wrote a `where` function that properly filters nested fields. At a quick glance, it looks like a good test, but it hasn't really tested anything. What's important is that you interfaced with the firestore API properly. i.e. `expect(mockWhere).toHaveBeenCalledWith('species.type', '==', 'mammal')` -- what it returns is irrelevant because you'd never question what firestore returns.

But I admit there are probably use-cases I'm not thinking of, so I'm curious to here your thoughts. I just don't want to get into feature parody hell, as it would take too much maintenance time on this library as Google inevitably updates their APIs and behaviors.

**Comment by sbatson5** [comment]
> That said, I actually intend to spend sometime helping this library evolve if possible, just won't have much time to do so for the next months haha

Some PR's and help would be great 😅 
I love that others have found this library useful, but it's hard to keep up with it with my day job -- especially considering there are so many aspects to firestore I haven't used, so can't confidently write mocks/tests
